name: protasks
description: A Flutetr Bloc Architecture project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.5.0
  auto_size_text: ^3.0.0-nullsafety.0
  awesome_notifications: ^0.0.6+9
  bloc: ^7.1.0
  cloud_firestore: ^2.4.0
  cloud_functions: ^3.0.0
  cupertino_icons: ^1.0.3
  enum_to_string: ^2.0.1
  firebase_app_check: ^0.0.2
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_crashlytics: ^2.1.1
  firebase_dynamic_links: ^2.0.7
  firebase_performance: ^0.7.0+7
  firebase_remote_config: ^0.10.0+3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  flutter_keyboard_visibility: ^5.0.2
  fluttertoast: ^8.0.7
  font_awesome_flutter: ^9.1.0
  google_mobile_ads: ^0.13.3
  google_sign_in: ^5.0.7
  hydrated_bloc: ^7.0.1
  implicitly_animated_reorderable_list: ^0.4.0
  internet_connection_checker: ^0.0.1+2
  intl: ^0.17.0
  package_info_plus: ^1.0.4
  path_provider: ^2.0.2
  rxdart: ^0.27.1
  sembast: ^3.0.3
  share_plus: ^2.1.4
  shimmer: ^2.0.0
  swipe_to: ^0.1.0-nullsafety.1
  url_launcher: ^6.0.9
  uuid: ^3.0.4
  version: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.1
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/logo/app_icon_ios.png"
  image_path_android: "assets/images/logo/app_icon.png"
  adaptive_icon_background: "#1E2435"
  adaptive_icon_foreground: "assets/images/logo/app_icon_foreground_final.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_foreground.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
        - weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
        - weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - weight: 400

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - weight: 400
